<a href="https://colab.research.google.com/github/karthikeyathotak4/TensorFlow_Learning/blob/main/0x00_Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **In this File, I am going to cover most fundamental concepts of tensors using TensorFlow**
   More Specifically, I will cover:
        # Introduction to tensors
        # Getting Information from tensors
        # Manipulating tensors
        # Using @tf.function ( a way to speed up your regular Python Functions )
        # We are going to use GPUs with TensorFlow
        # Finally let's do some Exercises to try

# **1. Intro to Tensors**

In [6]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.4.1


In [9]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [12]:
# Check the number of dimensions of a tensor( ndim stands for number of dimensions )
scalar.ndim

0

In [15]:
# Create a Vector
verctor = tf.constant([10, 10])
verctor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [17]:
# Check the dimension of our vector
verctor.ndim

1

In [19]:
# Create a matrix ( has more than 1 dimension)
matrix = tf.constant([[10, 7], [7, 10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [20]:
matrix.ndim

2

In [22]:
# Create another matrix
another_matrix = tf.constant([[4.,2.], [5.,7.], [6., 14.]], dtype=tf.float16) # Specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 4.,  2.],
       [ 5.,  7.],
       [ 6., 14.]], dtype=float16)>

In [23]:
# What's the number number dimenision of another_matrix?
another_matrix.ndim

2

In [29]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]],
                     [[13, 14, 15],
                      [16, 17, 18]],
                      [[19, 20, 21],
                       [22, 23, 24]]])
tensor

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

In [30]:
tensor.ndim

3

# **What we've created so far:**
  * Scalar:  a single number
  * Vector:  a number with direction(e.g wind speed and direction)
  * Matrix:  a 2-dimensional array of numbers
  * Tensor:  an n number of dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vertor)

### Creating tensors with `tf.Vairable`

In [32]:
# Create the same tensor  with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangealbe_tensor = tf.constant([10, 7])

changeable_tensor, unchangealbe_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [34]:
# Let's try change one of the elements in out changeable tensor
changeable_tensor[0] = 7

changeable_tensor

TypeError: ignored

In [35]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [38]:
# Let's try change our unchangable tensor
unchangeable_tensor[0].assign(2)

NameError: ignored

**🔑 Note:**
Rarely in practice will you need to decide whether to use `tf.constant` or `tf.Variable` to create tensors, as TensorFlow does this for you. However, if in doubt, use `tf.constant` and change it later if needed

### Creating random tensors

Random tensors are tensors of some abit

In [43]:
# Create two random ( but the same) tensors

random_1 = tf.random.Generator.from_seed(42)  # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_1

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_2 == random_1

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [ ]:
# Start here https://youtu.be/tpCFfeUEGs8?t=5541