<a href="https://colab.research.google.com/github/karthikeyathotak4/TensorFlow_Learning/blob/main/0x00_Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **In this File, I am going to cover most fundamental concepts of tensors using TensorFlow**
   More Specifically, I will cover:
        # Introduction to tensors
        # Getting Information from tensors
        # Manipulating tensors
        # Using @tf.function ( a way to speed up your regular Python Functions )
        # We are going to use GPUs with TensorFlow
        # Finally let's do some Exercises to try

# **1. Intro to Tensors**

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.4.1


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor( ndim stands for number of dimensions )
scalar.ndim

0

In [ ]:
# Create a Vector
verctor = tf.constant([10, 10])
verctor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
verctor.ndim

1

In [ ]:
# Create a matrix ( has more than 1 dimension)
matrix = tf.constant([[10, 7], [7, 10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[4.,2.], [5.,7.], [6., 14.]], dtype=tf.float16) # Specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 4.,  2.],
       [ 5.,  7.],
       [ 6., 14.]], dtype=float16)>

In [ ]:
# What's the number number dimenision of another_matrix?
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]],
                     [[13, 14, 15],
                      [16, 17, 18]],
                      [[19, 20, 21],
                       [22, 23, 24]]])
tensor

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# **What we've created so far:**
  * Scalar:  a single number
  * Vector:  a number with direction(e.g wind speed and direction)
  * Matrix:  a 2-dimensional array of numbers
  * Tensor:  an n number of dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vertor)

### Creating tensors with `tf.Vairable`

In [ ]:
# Create the same tensor  with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangealbe_tensor = tf.constant([10, 7])

changeable_tensor, unchangealbe_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one of the elements in out changeable tensor
changeable_tensor[0] = 7

changeable_tensor

TypeError: ignored

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Let's try change our unchangable tensor
unchangeable_tensor[0].assign(2)

**🔑 Note:**
Rarely in practice will you need to decide whether to use `tf.constant` or `tf.Variable` to create tensors, as TensorFlow does this for you. However, if in doubt, use `tf.constant` and change it later if needed

### Creating random tensors

Random tensors are tensors of some abit

In [ ]:
# Create two random ( but the same) tensors

random_1 = tf.random.Generator.from_seed(42)  # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_1

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_2 == random_1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you wnant to shuffle your data so the inhernet order doesn't effect learning )

not_shuffled = tf.constant([[10, 7],
                          [3, 4],
                          [2, 5]])

# Shuffle our non-shuffle tensor

tf.random.shuffle(not_shuffled)

In [ ]:
# Shuffle our non-shuffle tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

In [ ]:
not_shuffled

### 📝 **HomeWork:** Read through TensorFlow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them

Readig the documentation:
    What is seed in TernsorFlow?
      Seed is an abbreviation of the stander term "random seed". Tensorflow operators that produce random results accept an optional seed parameter.If pass the same number of two instances of the same operator, they will produce the same squence of results.

  `tf.random.set_seed` = Sets the global random seed

  `tf.random.shuffle(VALUE, seed= INT or FLOAT)` = Sets the operational seed

Rules:
  Operations that relys on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

  It interactions with operation-level seeds is as follows:

    1. If neither the global and the operation seed is set: A randomly picked seed is used for it

    2. If the graph-level seed is set, but the operation seed is not:  The system will pick the operation seed in conjection with the graph-level seed so that it gets a unique random sequence.

    3. If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.

    4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.


In [ ]:
# ------------------------------------------------------------------------------------ Home Work ---------------------------------------------------------------------------------------------------------------------------------

# ------------------- Tensor number 1 ---------------------

# Creating a tensor with tf.constant

tensor_1 = tf.random.Generator.from_seed(10)
tensor_1 = tensor_1.normal(shape=(3,2))

print("This is the Result before shuffling :\n", tensor_1)

print("\n")
print("This is the result after shuffling :\n")
tf.random.shuffle(tensor_1)



This is the Result before shuffling :
 tf.Tensor(
[[ 1.0278524   0.27974114]
 [-0.01347923  1.845181  ]
 [ 0.97061104 -1.0242516 ]], shape=(3, 2), dtype=float32)


This is the result after shuffling :



<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.01347923,  1.845181  ],
       [ 0.97061104, -1.0242516 ],
       [ 1.0278524 ,  0.27974114]], dtype=float32)>

In [ ]:
# ------------------ Tensor Number 2 ------------------
tensor_2 = tf.random.Generator.from_seed(100)
tensor_2 = tensor_2.normal(shape=(4, 4))



print("Before shuffling the tensors : \n", tensor_2)

# Shuffling the tensors
tensor_2 = tf.random.shuffle(tensor_2)
print("After shuffling the tensors : \n", tensor_2)

Before shuffling the tensors : 
 tf.Tensor(
[[-1.0130816   0.28291714  1.2132233   0.46988967]
 [ 0.37944323 -0.6664026   0.6054596   0.19181173]
 [ 0.8045827   0.4769051  -0.7812124  -0.996891  ]
 [ 0.33149973 -0.5445254   1.5222508   0.59303206]], shape=(4, 4), dtype=float32)
After shuffling the tensors : 
 tf.Tensor(
[[ 0.8045827   0.4769051  -0.7812124  -0.996891  ]
 [-1.0130816   0.28291714  1.2132233   0.46988967]
 [ 0.33149973 -0.5445254   1.5222508   0.59303206]
 [ 0.37944323 -0.6664026   0.6054596   0.19181173]], shape=(4, 4), dtype=float32)


In [ ]:
# --------------------- Tensor Number 3 ----------------
S = tf.random.set_seed(9)
tensor_3 = tf.random.Generator.from_seed(1000)
tensor_3 = tensor_3.normal(shape=(6, 6))
print("Dimension of tensor_3 is : ", tensor_3.ndim)
print("Befor Shuffling the tensors: \n", tensor_3)

# Shuffling the tensors
tensor_3 = tf.random.shuffle(tensor_3)
print("After shuflling the tensors : \n", tensor_3)

Dimension of tensor_3 is :  2
Befor Shuffling the tensors: 
 tf.Tensor(
[[ 1.428492   -0.11131959 -0.98949283 -0.12332226 -1.9408084   0.5852516 ]
 [ 0.24558403 -1.0308076   0.18177792  1.3797795  -0.7982999   0.84330505]
 [ 0.15101781  0.22444367 -0.0479347   1.1848813   1.902318    0.30197945]
 [-0.69273     0.3778172   0.0679005   0.03989154  0.8619055  -0.38141087]
 [-0.23930925  0.24173513  0.7105374  -1.4099492  -0.67304814  0.0968298 ]
 [ 1.5919992   1.0718066  -0.39992824 -0.1343118  -0.6745226  -0.20809175]], shape=(6, 6), dtype=float32)
After shuflling the tensors : 
 tf.Tensor(
[[-0.23930925  0.24173513  0.7105374  -1.4099492  -0.67304814  0.0968298 ]
 [ 1.428492   -0.11131959 -0.98949283 -0.12332226 -1.9408084   0.5852516 ]
 [ 0.24558403 -1.0308076   0.18177792  1.3797795  -0.7982999   0.84330505]
 [ 0.15101781  0.22444367 -0.0479347   1.1848813   1.902318    0.30197945]
 [ 1.5919992   1.0718066  -0.39992824 -0.1343118  -0.6745226  -0.20809175]
 [-0.69273     0.3778172   0.

In [ ]:
# Tensor Number 4
import tensorflow as tf

tensor_4 = tf.random.Generator.from_seed(1000)
tensor_4 = tensor_4.normal(shape=(10000, 10000)) # Ten Thousand

print("There are ",tensor_4.ndim,"Dimensions")
# Print Values before the Shuffling
print("Values Before Shuffling :\n", tensor_4)



# Shuffling the tensor value
tensor_4 = tf.random.shuffle(tensor_4)

# Printing the Values After Shuffling
print("Values after shuffling : \n", tensor_4)

There are  2 Dimensions
Values Before Shuffling :
 tf.Tensor(
[[ 1.428492   -0.11131959 -0.98949283 ...  0.4800271  -2.2037764
  -0.49362984]
 [ 0.7650626  -0.4262426   0.2981213  ...  2.3630762   1.4497685
  -0.44194874]
 [ 0.35772958 -2.143428    0.8555861  ... -1.3436735   0.37121654
   0.4036901 ]
 ...
 [ 0.24998242 -1.3887842  -0.94313496 ... -0.3383281   0.14922103
   0.99781376]
 [ 0.21825196  0.27063513 -0.6339465  ...  0.9512149  -1.9526484
  -1.1082535 ]
 [-0.8324159   0.59630764 -0.05518086 ... -2.5894506   1.1696477
  -0.693894  ]], shape=(10000, 10000), dtype=float32)
Values after shuffling : 
 tf.Tensor(
[[ 1.5229791  -1.2697895   0.0098869  ...  1.1849686   1.3079083
  -1.4683725 ]
 [ 2.581934    0.86931854 -0.5719408  ...  0.10543409  0.12852377
  -0.45283732]
 [-0.5704333   1.898085   -0.35084242 ... -1.0208234  -0.17311518
  -0.35269386]
 ...
 [-1.0570074   0.34339646 -0.61685556 ... -1.1676439  -0.4576272
   0.5401313 ]
 [-1.6292181   1.7154305   0.38126457 ...  0.37

In [ ]:
import tensorflow as tf

tensor_5 = tf.random.Generator.from_seed(0)
tensor_5 = tensor_5.normal(shape=(20,2))

# Prints the diemensions in tensor_5
print("There are ",tensor_5.ndim,"in tensor_5")

# Printing the values before shuffling
print("Value of tensor_5: \n", tensor_5)

# Shuffling the tensor_5's value
tensor_5 = tf.random.shuffle(tensor_5)

# Prints the value of tensor_5 after Shuffling
print("Values after shuffling tensor_5 \n", tensor_5)

There are  2 in tensor_5
Value of tensor_5: 
 tf.Tensor(
[[-1.3544159   0.70454913]
 [ 0.03666191  0.86918795]
 [ 0.43842274 -0.53439844]
 [-0.07710262  1.5658046 ]
 [-0.1012345  -0.2744976 ]
 [ 1.4204658   1.2609464 ]
 [-0.43640924 -1.9633987 ]
 [-0.06452483 -1.056841  ]
 [ 1.0019137   0.6735137 ]
 [ 0.06987712 -1.4077919 ]
 [ 1.0278524   0.27974114]
 [-0.01347923  1.845181  ]
 [ 0.97061104 -1.0242516 ]
 [-0.6544423  -0.29738766]
 [-1.3240396   0.28785667]
 [-0.8757901  -0.08857018]
 [ 0.69211644  0.84215707]
 [-0.06378496  0.92800784]
 [-0.6039789  -0.1766927 ]
 [ 0.04221033  0.29037967]], shape=(20, 2), dtype=float32)
Values after shuffling tensor_5 
 tf.Tensor(
[[-0.1012345  -0.2744976 ]
 [ 1.0278524   0.27974114]
 [-0.8757901  -0.08857018]
 [ 1.0019137   0.6735137 ]
 [ 0.06987712 -1.4077919 ]
 [-0.07710262  1.5658046 ]
 [ 0.03666191  0.86918795]
 [-0.06452483 -1.056841  ]
 [-0.01347923  1.845181  ]
 [-0.06378496  0.92800784]
 [-0.6544423  -0.29738766]
 [-1.3240396   0.28785667]
 [

### Other ways to make tensors

In [ ]:
# Created a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

### Create a tensor of all zeroes

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on GPU ( mus faster for numerical computing).


In [ ]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumpPy array between 1 and 25
numpy_A

# X = tf.constant(som_matrix) # capital for matrix or tensor
# y = tf.constant(verctor) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

# Getting information from tensors


* Shape - The length( number of elements) of each of the dimensions of a tensor.CODE - `tensor.shape`
* Rank - The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n. CODE - `tensor.ndim`
* Axis or dimension - A particular dimension of a tensor.CODE- `tensor[0], tensor[: 1]..`
* Size - The total number of items in the tensor. CODE- `tf.size(tensor)`

In [ ]:
# Create a rank for tensor ( 4 dimensions)
rank_4_tensor = tf.zeros([2,3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
# Start at https://youtu.be/tpCFfeUEGs8?t=7243